"""Crear tabla componente_defectuoso con motivo

Revision ID: 43c94b4d5332
Revises: cfa01d3fee61
Create Date: 2025-03-20 20:21:58.096077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c94b4d5332'
down_revision = 'cfa01d3fee61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componente_defectuoso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.Text(), nullable=False))
        batch_op.alter_column('modelo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componente_defectuoso', schema=None) as batch_op:
        batch_op.alter_column('modelo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('motivo')

    # ### end Alembic commands ###
