"""Agregar relación computadora_id a accesorios

Revision ID: 5a74abe3f8d7
Revises: cd4dfa9b66f3
Create Date: 2025-04-04 20:57:41.558315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a74abe3f8d7'
down_revision = 'cd4dfa9b66f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('computadora_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'computadora', ['computadora_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('computadora_id')

    # ### end Alembic commands ###
