"""Agregar campo codigo_recuperacion

Revision ID: 716ef4c403cd
Revises: a4e162156b9b
Create Date: 2025-04-25 00:15:23.530758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716ef4c403cd'
down_revision = 'a4e162156b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_recuperacion', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('codigo_recuperacion')

    # ### end Alembic commands ###
