"""estructura inicial completa

Revision ID: 7bcff5d33d6d
Revises: 
Create Date: 2025-04-18 00:14:44.022547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bcff5d33d6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computadora_eliminada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_inventario', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('ubicacion_campus', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('monitor', sa.String(length=100), nullable=True),
    sa.Column('teclado', sa.String(length=100), nullable=True),
    sa.Column('monitor_obsoleto', sa.Boolean(), nullable=False),
    sa.Column('teclado_obsoleto', sa.Boolean(), nullable=False),
    sa.Column('tipo_propiedad', sa.String(length=10), nullable=False),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('empleado_nombre', sa.String(length=100), nullable=True),
    sa.Column('empleado_email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('puesto', sa.String(length=100), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reasignaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_equipo', sa.String(length=100), nullable=False),
    sa.Column('nomenclatura', sa.String(length=100), nullable=False),
    sa.Column('service_tag', sa.String(length=100), nullable=False),
    sa.Column('serie', sa.String(length=100), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('inventario', sa.String(length=100), nullable=False),
    sa.Column('fecha_traslado', sa.Date(), nullable=False),
    sa.Column('propiedad', sa.String(length=50), nullable=False),
    sa.Column('accesorios', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('unidad_emisor', sa.String(length=100), nullable=False),
    sa.Column('responsable_emisor', sa.String(length=100), nullable=False),
    sa.Column('correo_emisor', sa.String(length=100), nullable=False),
    sa.Column('empleado_emisor', sa.String(length=50), nullable=False),
    sa.Column('ubicacion_emisor', sa.String(length=100), nullable=False),
    sa.Column('unidad_receptor', sa.String(length=100), nullable=False),
    sa.Column('responsable_receptor', sa.String(length=100), nullable=False),
    sa.Column('correo_receptor', sa.String(length=100), nullable=False),
    sa.Column('empleado_receptor', sa.String(length=50), nullable=False),
    sa.Column('ubicacion_receptor', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('computadora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_inventario', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_campus', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('monitor', sa.String(length=100), nullable=True),
    sa.Column('teclado', sa.String(length=100), nullable=True),
    sa.Column('monitor_obsoleto', sa.Boolean(), nullable=False),
    sa.Column('teclado_obsoleto', sa.Boolean(), nullable=False),
    sa.Column('tipo_propiedad', sa.String(length=10), nullable=False),
    sa.Column('es_obsoleta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_inventario')
    )
    op.create_table('accesorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('numero_inventario', sa.String(length=100), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('computadora_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['computadora_id'], ['computadora.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('componente_defectuoso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_componente', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('inventario_componente', sa.String(length=100), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('fecha_marcado', sa.DateTime(), nullable=True),
    sa.Column('computadora_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['computadora_id'], ['computadora.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('migracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('computadora_id', sa.Integer(), nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=False),
    sa.Column('receptor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_migracion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['computadora_id'], ['computadora.id'], ),
    sa.ForeignKeyConstraint(['emisor_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['empleado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migracion')
    op.drop_table('componente_defectuoso')
    op.drop_table('accesorio')
    op.drop_table('computadora')
    op.drop_table('usuario')
    op.drop_table('reasignaciones')
    op.drop_table('empleado')
    op.drop_table('computadora_eliminada')
    # ### end Alembic commands ###
