"""Migración limpia final

Revision ID: 7cc5aba47975
Revises: 
Create Date: 2025-04-25 02:22:48.346180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc5aba47975'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computadora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_recuperacion', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('codigo_recuperacion')

    with op.batch_alter_table('computadora', schema=None) as batch_op:
        batch_op.drop_column('observaciones')

    # ### end Alembic commands ###
