"""Agregar campo observaciones a computadora

Revision ID: a4e162156b9b
Revises: 2e696449557c
Create Date: 2025-04-24 22:22:00.132045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e162156b9b'
down_revision = '2e696449557c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computadora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computadora', schema=None) as batch_op:
        batch_op.drop_column('observaciones')

    # ### end Alembic commands ###
