"""Migración completa con empleado_id

Revision ID: af2d5a1aa7ff
Revises: 
Create Date: 2025-04-22 22:30:16.505401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2d5a1aa7ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componente_defectuoso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empleado_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'empleado', ['empleado_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componente_defectuoso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empleado_id')

    # ### end Alembic commands ###
