"""Soporte delete cascade en componentes obsoletos

Revision ID: cd4dfa9b66f3
Revises: e9a23beb3f64
Create Date: 2025-04-03 20:00:21.999697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4dfa9b66f3'
down_revision = 'e9a23beb3f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componente_defectuoso', schema=None) as batch_op:
        batch_op.drop_constraint('componente_defectuoso_computadora_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'computadora', ['computadora_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componente_defectuoso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('componente_defectuoso_computadora_id_fkey', 'computadora', ['computadora_id'], ['id'])

    # ### end Alembic commands ###
