"""Agregar tabla Accesorio

Revision ID: e9a23beb3f64
Revises: 43c94b4d5332
Create Date: 2025-04-01 19:36:18.191030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a23beb3f64'
down_revision = '43c94b4d5332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('numero_inventario', sa.String(length=100), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accesorio')
    # ### end Alembic commands ###
