"""Permitir computadora_id NULL en ComponenteDefectuoso

Revision ID: fa2595f921ef
Revises: 5a74abe3f8d7
Create Date: 2025-04-05 00:31:18.868620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2595f921ef'
down_revision = '5a74abe3f8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componente_defectuoso', schema=None) as batch_op:
        batch_op.alter_column('computadora_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componente_defectuoso', schema=None) as batch_op:
        batch_op.alter_column('computadora_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
